version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-send-emails"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-msxwtsh9fhkm"
s3_prefix = "sam-send-emails"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
